# Generated by Django 3.2.16 on 2022-11-30 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 8, 56, 24, 378563), verbose_name='Время жизни'),
        ),
    ]
