# Generated by Django 4.1.1 on 2022-12-01 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_question_description_question_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description2',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='images/question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 18, 59, 55, 130004), verbose_name='Время жизни'),
        ),
    ]
