# Generated by Django 4.1.1 on 2022-12-01 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_question_life_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 20, 19, 17, 165070), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
