# Generated by Django 4.1.1 on 2022-12-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_voted_alter_question_life_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 20, 33, 47, 924432), verbose_name='Время жизни'),
        ),
    ]
