# Generated by Django 4.1.1 on 2022-12-01 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_question_life_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='voted',
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 21, 9, 54, 394594), verbose_name='Время жизни'),
        ),
    ]
